### ISSUE TITLE
Question: How to edit config.yml

### ISSUE THREAD

**Issue by joekerna** [ChristophWurst/signal-web-gateway#1]
This no issue, but a question I'm struggling with:

In the README it says 

> Edit the .config/config.yml to suit your needs 

How do I do that? How can I open that file in (preferably) vi?

I've edited the local file with my phone-number and then ran
`docker cp config.yml helper:/signal/.config/`

and then 
`docker run --rm -it -v signal-web-gateway_config:/signal/.config -v signal-web-gateway_storage:/signal/.storage registry.gitlab.com/morph027/signal-web-gateway:master register`

But it's till using the old +1... phone number

**Comment by ChristophWurst** [comment]
cc @morph027 :)

**Comment by ChristophWurst** [comment]
(this repo is a clone of https://gitlab.com/morph027/signal-web-gateway)

**Comment by morph027** [comment]
Are you using the Docker volumes (e.g. `signal-web-gateway_config`) as referred in the README?

`docker volume create signal-web-gateway_config`

If so, you should be able to enter the running signal container (`docker exec -it <id-or-name> sh`) and edit your file. After that, `docker restart <id-or-name>`.

Or you can inspect the volume and edit the file in it's filesystem location.

`docker volume inspect signal-web-gateway_config | grep Mountpoint` gives you the location. Better stop the container before editing this file.

**Comment by joekerna** [comment]
Thank you! That worked perfectly....

No I'm stuck with the next error but this issue can be closed

> Enter verification code>720035                                                                                                                                                                                                             
> code1: 720035                                                                                                                                                                                                                              
> RegistrationLockFailure                                                                                                                                                                                                                    
>  Time to wait                                                                                                                                                                                                                              
>  {"timeRemaining":564905569,"storageCredentials":null}
